apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: bloomlater
    app.kubernetes.io/component: backend
spec:
  selector:
    app: bloomlater-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
