apiVersion: v1
kind: Secret

metadata:
  name: bloom-back-secret
  namespace: bloom-ns


type: Opaque

stringData:
  MONGO_URI: mongodb://bloomlater:changeme_super_secret@bloom-mongo-svc:27017/bloomlater?authSource=admin
  JWT_ACCESS_SECRET: your_access_secret_here
  JWT_REFRESH_SECRET: your_refresh_secret_here