apiVersion: v1
kind: Service

metadata:
  name: bloom-back-svc
  namespace: bloom-ns

spec:
  selector:
    app: bloom-back
  
  ports:
    - port: 4000
      targetPort: 4000
  
  type: ClusterIP