apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: bloomlater
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: bloomlater-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
