apiVersion: v1
kind: Secret

metadata:
  name: bloom-mongo-secret
  namespace: bloom-ns

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: bloomlater
  MONGO_INITDB_ROOT_PASSWORD: changeme_super_secret
