apiVersion: v1
kind: Service
metadata:
  name: bloom-mongo-svc
  namespace: bloom-ns
spec:
  selector:
    app: bloom-mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP