apiVersion: v1
kind: ConfigMap
metadata:
  name: bloomlater-config
  labels:
    app.kubernetes.io/name: bloomlater
data:
  NODE_ENV: "production"
  PORT: "4000"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  STORAGE_DRIVER: "local"
  UPLOAD_DIR: "/app/uploads"
  LOG_LEVEL: "info"
